const zeichenListe = [
    { deutsch: "Mensch",             chinesisch: "人",   pinyin: "rén" },
    { deutsch: "Mann",               chinesisch: "男",   pinyin: "nán" },
    { deutsch: "Wasser",             chinesisch: "水",   pinyin: "shuǐ" },
    { deutsch: "Geld",               chinesisch: "钱",   pinyin: "qián" },
    { deutsch: "Hand",               chinesisch: "手",   pinyin: "shǒu" },
    { deutsch: "Kopf",               chinesisch: "头",   pinyin: "tóu" },
    { deutsch: "gut",                chinesisch: "好",   pinyin: "hǎo" },
    { deutsch: "schlecht",           chinesisch: "坏",   pinyin: "huài" },
    { deutsch: "groß",               chinesisch: "大",   pinyin: "dà" },
    { deutsch: "klein",              chinesisch: "小",   pinyin: "xiǎo" },
    { deutsch: "gehen",              chinesisch: "走",   pinyin: "zǒu" },
    { deutsch: "kaufen",             chinesisch: "买",   pinyin: "mǎi" },
    { deutsch: "essen",              chinesisch: "吃",   pinyin: "chī" },
    { deutsch: "trinken",            chinesisch: "喝",   pinyin: "hē" },
    { deutsch: "Himmel / Tag",       chinesisch: "天",   pinyin: "tiān" },
    { deutsch: "Erde / Boden",       chinesisch: "地",   pinyin: "dì" },
    { deutsch: "oben / auf",         chinesisch: "上",   pinyin: "shàng" },
    { deutsch: "unten / unter",      chinesisch: "下",   pinyin: "xià" },
    { deutsch: "Mitte / Zentrum",    chinesisch: "中",   pinyin: "zhōng" },
    { deutsch: "Land / Staat",       chinesisch: "国",   pinyin: "guó" },
    { deutsch: "lernen / studieren", chinesisch: "学",   pinyin: "xué" },
    { deutsch: "leben",              chinesisch: "生",   pinyin: "shēng" },
    { deutsch: "lieben",             chinesisch: "爱",   pinyin: "ài" },
    { deutsch: "Familie / Zuhause",  chinesisch: "家",   pinyin: "jiā" },
    { deutsch: "Kind",               chinesisch: "子",   pinyin: "zǐ" },
    { deutsch: "Mutter",             chinesisch: "母",   pinyin: "mǔ" },
    { deutsch: "Vater",              chinesisch: "父",   pinyin: "fù" },
    { deutsch: "Freund",             chinesisch: "友",   pinyin: "yǒu" },
    { deutsch: "sehen",              chinesisch: "见",   pinyin: "jiàn" },
    { deutsch: "sprechen / sagen",   chinesisch: "说",   pinyin: "shuō" },
    { deutsch: "kommen",             chinesisch: "来",   pinyin: "lái" },
    { deutsch: "gehen",              chinesisch: "去",   pinyin: "qù" },
    { deutsch: "viel",               chinesisch: "多",   pinyin: "duō" },
    { deutsch: "wenig",              chinesisch: "少",   pinyin: "shǎo" },
    { deutsch: "nicht (Verneinung)", chinesisch: "不",   pinyin: "bù" },
    { deutsch: "ich",                chinesisch: "我",   pinyin: "wǒ" },
    { deutsch: "er",                 chinesisch: "他",   pinyin: "tā" },
    { deutsch: "haben",              chinesisch: "有",   pinyin: "yǒu" },
    { deutsch: "ich möchte/will",    chinesisch: "我想", pinyin: "wǒ xiǎng" },
    { deutsch: "danke",              chinesisch: "谢谢", pinyin: "xièxie" },
    { deutsch: "Sonne",            chinesisch: "日", pinyin: "rì" },
    { deutsch: "Mond",             chinesisch: "月", pinyin: "yuè" },
    { deutsch: "Berg",             chinesisch: "山", pinyin: "shān" },
    { deutsch: "Feuer",            chinesisch: "火", pinyin: "huǒ" },
    { deutsch: "Baum",             chinesisch: "木", pinyin: "mù" },
    { deutsch: "Wald",             chinesisch: "林", pinyin: "lín" },
    { deutsch: "Mund",             chinesisch: "口", pinyin: "kǒu" },
    { deutsch: "Auge",             chinesisch: "目", pinyin: "mù" },
    { deutsch: "Ohr",              chinesisch: "耳", pinyin: "ěr" },
    { deutsch: "Herz",             chinesisch: "心", pinyin: "xīn" },
    { deutsch: "Fuß",              chinesisch: "足", pinyin: "zú" },
    { deutsch: "Kraft",            chinesisch: "力", pinyin: "lì" },
    { deutsch: "Tor",              chinesisch: "门", pinyin: "mén" },
    { deutsch: "Auto",             chinesisch: "车", pinyin: "chē" },
    { deutsch: "Regen",            chinesisch: "雨", pinyin: "yǔ" },
    { deutsch: "Fisch",            chinesisch: "鱼", pinyin: "yú" },
    { deutsch: "Hund",             chinesisch: "犬", pinyin: "quǎn" },
    { deutsch: "Pferd",            chinesisch: "马", pinyin: "mǎ" },
    { deutsch: "Frau",             chinesisch: "女", pinyin: "nǚ" },
    { deutsch: "Tag / Nummer",     chinesisch: "号", pinyin: "hào" },
    { deutsch: "sehen / anschauen",   chinesisch: "看", pinyin: "kàn" },
    { deutsch: "hören",               chinesisch: "听", pinyin: "tīng" },
    { deutsch: "denken",              chinesisch: "想", pinyin: "xiǎng" },
    { deutsch: "wissen / kennen",     chinesisch: "知", pinyin: "zhī" },
    { deutsch: "arbeiten",            chinesisch: "做", pinyin: "zuò" },
    { deutsch: "geben",               chinesisch: "给", pinyin: "gěi" },
    { deutsch: "fragen",              chinesisch: "问", pinyin: "wèn" },
    { deutsch: "neu",                 chinesisch: "新", pinyin: "xīn" },
    { deutsch: "alt",                 chinesisch: "老", pinyin: "lǎo" },
    { deutsch: "schnell",             chinesisch: "快", pinyin: "kuài" },
    { deutsch: "und",                 chinesisch: "和", pinyin: "hé" },
        { deutsch: "sein",                chinesisch: "是",   pinyin: "shì" },
    { deutsch: "Mensch / Leute",      chinesisch: "们",   pinyin: "men" },
    { deutsch: "du",                  chinesisch: "你",   pinyin: "nǐ" },
    { deutsch: "sie (Person)",        chinesisch: "她",   pinyin: "tā" },
    { deutsch: "dies / dieses",       chinesisch: "这",   pinyin: "zhè" },
    { deutsch: "jenes",               chinesisch: "那",   pinyin: "nà" },
    { deutsch: "hier",                chinesisch: "这儿", pinyin: "zhèr" },
    { deutsch: "dort",                chinesisch: "那儿", pinyin: "nàr" },
    { deutsch: "wer",                 chinesisch: "谁",   pinyin: "shéi" },
    { deutsch: "was",                 chinesisch: "什么", pinyin: "shénme" },
    { deutsch: "wo",                  chinesisch: "哪",   pinyin: "nǎ" },
    { deutsch: "warum",               chinesisch: "为什么", pinyin: "wèishénme" },
    { deutsch: "wie",                 chinesisch: "怎",   pinyin: "zěn" },
    { deutsch: "ja / richtig",        chinesisch: "对",   pinyin: "duì" },
    { deutsch: "können",              chinesisch: "能",   pinyin: "néng" },
    { deutsch: "mögen",               chinesisch: "喜欢", pinyin: "xǐhuan" },
    { deutsch: "wollen",              chinesisch: "要",   pinyin: "yào" },
    { deutsch: "geben (existiert)",   chinesisch: "在",   pinyin: "zài" },
    { deutsch: "zurückkehren",        chinesisch: "回",   pinyin: "huí" },
    { deutsch: "öffnen",              chinesisch: "开",   pinyin: "kāi" },
    { deutsch: "schließen",           chinesisch: "关",   pinyin: "guān" },
    { deutsch: "hoch",                chinesisch: "高",   pinyin: "gāo" },
    { deutsch: "niedrig",             chinesisch: "低",   pinyin: "dī" },
    { deutsch: "lang",                chinesisch: "长",   pinyin: "cháng" },
    { deutsch: "kurz",                chinesisch: "短",   pinyin: "duǎn" },
    { deutsch: "heute",               chinesisch: "今",   pinyin: "jīn" },
    { deutsch: "Zeit",                chinesisch: "时",   pinyin: "shí" },
    { deutsch: "vor",                 chinesisch: "前",   pinyin: "qián" },
    { deutsch: "nach / hinter",       chinesisch: "后",   pinyin: "hòu" },
    { deutsch: "auch",                chinesisch: "也",   pinyin: "yě" }
]
