const zeichenListe = [
    { deutsch: "Mensch", chinesisch: "人", pinyin: "rén" },
    { deutsch: "Mann", chinesisch: "男", pinyin: "nán" },
    { deutsch: "Wasser", chinesisch: "水", pinyin: "shuǐ" },
    { deutsch: "Geld", chinesisch: "钱", pinyin: "qián" },
    { deutsch: "Hand", chinesisch: "手", pinyin: "shǒu" },
    { deutsch: "Kopf", chinesisch: "头", pinyin: "tóu" },
    { deutsch: "gut", chinesisch: "好", pinyin: "hǎo" },
    { deutsch: "schlecht", chinesisch: "坏", pinyin: "huài" },
    { deutsch: "groß", chinesisch: "大", pinyin: "dà" },
    { deutsch: "klein", chinesisch: "小", pinyin: "xiǎo" },
    { deutsch: "gehen", chinesisch: "走", pinyin: "zǒu" },
    { deutsch: "kaufen", chinesisch: "买", pinyin: "mǎi" },
    { deutsch: "essen", chinesisch: "吃", pinyin: "chī" },
    { deutsch: "trinken", chinesisch: "喝", pinyin: "hē" },
    { deutsch: "Himmel / Tag", chinesisch: "天", pinyin: "tiān" },
    { deutsch: "Erde / Boden", chinesisch: "地", pinyin: "dì" },
    { deutsch: "oben / auf", chinesisch: "上", pinyin: "shàng" },
    { deutsch: "unten / unter", chinesisch: "下", pinyin: "xià" },
    { deutsch: "Mitte / Zentrum", chinesisch: "中", pinyin: "zhōng" },
    { deutsch: "Land / Staat", chinesisch: "国", pinyin: "guó" },
    { deutsch: "lernen / studieren", chinesisch: "学", pinyin: "xué" },
    { deutsch: "leben", chinesisch: "生", pinyin: "shēng" },
    { deutsch: "lieben", chinesisch: "爱", pinyin: "ài" },
    { deutsch: "Familie / Zuhause", chinesisch: "家", pinyin: "jiā" },
    { deutsch: "Kind", chinesisch: "子", pinyin: "zǐ" },
    { deutsch: "Mutter", chinesisch: "母", pinyin: "mǔ" },
    { deutsch: "Vater", chinesisch: "父", pinyin: "fù" },
    { deutsch: "Freund", chinesisch: "友", pinyin: "yǒu" },
    { deutsch: "sehen", chinesisch: "见", pinyin: "jiàn" },
    { deutsch: "sprechen / sagen", chinesisch: "说", pinyin: "shuō" },
    { deutsch: "kommen", chinesisch: "来", pinyin: "lái" },
    { deutsch: "gehen", chinesisch: "去", pinyin: "qù" },
    { deutsch: "viel", chinesisch: "多", pinyin: "duō" },
    { deutsch: "wenig", chinesisch: "少", pinyin: "shǎo" },
    { deutsch: "nicht (Verneinung)", chinesisch: "不", pinyin: "bù" },
    { deutsch: "ich", chinesisch: "我", pinyin: "wǒ" },
    { deutsch: "er", chinesisch: "他", pinyin: "tā" },
    { deutsch: "haben", chinesisch: "有", pinyin: "yǒu" },
    { deutsch: "ich möchte/will", chinesisch: "我想", pinyin: "wǒ xiǎng" },
    { deutsch: "danke", chinesisch: "谢谢", pinyin: "xièxie" }
]